<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNDB0013" name="com.qait.automation.stik.test.TC_025" tests="8" failures="6" timestamp="6 Jan 2014 11:25:17 GMT" time="5.382" errors="1">
  <testcase name="C_Navigate_To_Mail_Panel" time="0.000" classname="com.qait.automation.stik.test.TC_025"/>
  <testcase name="A_launch_URL_Navgiate_to_Stick_HomePage" time="2.218" classname="com.qait.automation.stik.test.TC_025">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at com.qait.automation.stik.actionfixtures.BaseFixture.launchUrl(BaseFixture.java:253)
	at com.qait.automation.stik.test.TC_025.A_launch_URL_Navgiate_to_Stick_HomePage(TC_025.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- A_launch_URL_Navgiate_to_Stick_HomePage -->
  <testcase name="G_signOut" time="0.000" classname="com.qait.automation.stik.test.TC_025"/>
  <testcase name="D_Import_Email_Contact" time="0.000" classname="com.qait.automation.stik.test.TC_025"/>
  <testcase name="F_Select_Industry_PhoneNumber_ZipCode_And_Click_Create_Profile" time="0.001" classname="com.qait.automation.stik.test.TC_025"/>
  <testcase name="setup" time="3.162" classname="com.qait.automation.stik.test.TC_025"/>
  <testcase name="B_Sign_Up_Using_With_LinkedIn_Using_Link_On_Professional_Sign_Up_Page" time="0.001" classname="com.qait.automation.stik.test.TC_025"/>
  <testcase name="E_Click_Continue_And_Handle_Modal_Dailog_to_Send_Message" time="0.000" classname="com.qait.automation.stik.test.TC_025"/>
</testsuite> <!-- com.qait.automation.stik.test.TC_025 -->
