<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HPDA0161" name="com.qait.automation.stik.test.TC_001" tests="9" failures="3" timestamp="21 Feb 2014 04:59:40 GMT" time="123.100" errors="1">
  <testcase name="E_Is_My_Profile_Info_Page_Ok" time="5.036" classname="com.qait.automation.stik.test.TC_001">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at com.qait.automation.stik.actionfixtures.ProfileInfoPageFixture.isMyProfileInfoPageOk(ProfileInfoPageFixture.java:23)
	at com.qait.automation.stik.test.TC_001.E_Is_My_Profile_Info_Page_Ok(TC_001.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- E_Is_My_Profile_Info_Page_Ok -->
  <testcase name="B_Login_Using_FaceBook_Link_Given_On_Home_Page" time="84.653" classname="com.qait.automation.stik.test.TC_001"/>
  <testcase name="F_Update_Account_Info_Verify_Info_Gets_Updated_On_Profile_Page" time="0.001" classname="com.qait.automation.stik.test.TC_001"/>
  <testcase name="setup" time="7.097" classname="com.qait.automation.stik.test.TC_001"/>
  <testcase name="C_Verify_First_Name_Is_Displayed_On_Home_Page_After_Signing_Into_App" time="4.057" classname="com.qait.automation.stik.test.TC_001"/>
  <testcase name="H_signOut" time="0.001" classname="com.qait.automation.stik.test.TC_001"/>
  <testcase name="A_launch_URL_Navgiate_to_Stick_HomePage" time="13.268" classname="com.qait.automation.stik.test.TC_001"/>
  <testcase name="G_Is_My_Profile_Ok" time="0.000" classname="com.qait.automation.stik.test.TC_001"/>
  <testcase name="D_Navigate_To_Profile_Info_Page_Verify_Profile_Info_Page" time="8.987" classname="com.qait.automation.stik.test.TC_001"/>
</testsuite> <!-- com.qait.automation.stik.test.TC_001 -->
