<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HPDA0161" name="com.qait.automation.stik.test.TC_003" tests="4" failures="1" timestamp="25 Feb 2014 11:22:21 GMT" time="95.295" errors="1">
  <testcase name="A_launch_URL_Navgiate_to_Stick_HomePage" time="15.613" classname="com.qait.automation.stik.test.TC_003"/>
  <testcase name="setup" time="7.613" classname="com.qait.automation.stik.test.TC_003"/>
  <testcase name="tearDown" time="0.001" classname="com.qait.automation.stik.test.TC_003"/>
  <testcase name="B_Send_Review_Thru_CombinedWizard_Without_Existing_Session" time="72.068" classname="com.qait.automation.stik.test.TC_003">
    <error type="java.lang.AssertionError" message="Problem in adding contacts!! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Problem in adding contacts!! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.qait.automation.stik.actionfixtures.ReviewPageFixture.recommendProfessionalsToFriends(ReviewPageFixture.java:208)
	at com.qait.automation.stik.actionfixtures.ReviewPageFixture.sendReviewCombinedWizardAndVerifyGivenReviewAppearOnHomePage(ReviewPageFixture.java:51)
	at com.qait.automation.stik.test.TC_003.B_Send_Review_Thru_CombinedWizard_Without_Existing_Session(TC_003.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- B_Send_Review_Thru_CombinedWizard_Without_Existing_Session -->
</testsuite> <!-- com.qait.automation.stik.test.TC_003 -->
